BUILTIN_REPOS = {
    "abap",
    "apex",
    "azureresourcemanager",
    "c",
    "cloudformation",
    "cobol",
    "cpp",
    "csharpsquid",
    "css",
    "docker",
    "dart",
    "external_android-lint",
    "external_bandit",
    "external_cfn-lint",
    "external_checkstyle",
    "external_detekt",
    "external_eslint_repo",
    "external_fbcontrib",
    "external_findsecbugs",
    "external_flake8",
    "external_golint",
    "external_govet",
    "external_hadolint",
    "external_ktlint",
    "external_mypy",
    "external_phpstan",
    "external_pmd",
    "external_pmd_apex",
    "external_psalm",
    "external_pylint",
    "external_rubocop",
    "external_ruff",
    "external_scalastyle",
    "external_scapegoat",
    "external_spotbugs",
    "external_stylelint",
    "external_swiftlint",
    "external_tflint",
    "external_tslint_repo",
    "external_valgrind-c",
    "external_valgrind-cpp",
    "external_valgrind-objc",
    "ipython",
    "flex",
    "go",
    "java",
    "javabugs",
    "javascript",
    "javasecurity",
    "jcl",
    "jssecurity",
    "kotlin",
    "kubernetes",
    "objc",
    "php",
    "phpsecurity",
    "pli",
    "plsql",
    "python",
    "pythonbugs",
    "pythonsecurity",
    "roslyn.sonaranalyzer.security.cs",
    "rpg",
    "ruby",
    "scala",
    "secrets",
    "swift",
    "terraform",
    "text",
    "tsql",
    "tssecurity",
    "typescript",
    "vb",
    "vbnet",
    "Web",
    "xml"
}

REPORT_TASKS = [
    'getBranches',
    'getProjectPullRequests',
    'getRules',
    'getProfileRules',
    'getProjectAnalyses',
    'getProjectDetails',
    'getApplicationDetails',
    'getServerInfo',
    'getProjectBindings',
    'getGates',
    'getPlugins',
    'getDefaultTemplates',
    'getTemplates',
    'getPlugins',
    'getPortfolioDetails',
    'getPortfolioProjects',
    'getProfiles',
    'getProjectSettings',
    'getUsers',
    'getUsage'
]

MIGRATION_TASKS = [
    'getProfileUsers',
    'getApplications',
    'getPortfolioProjects',
    'getAcceptedIssues',
    'getSafeHotspots',
    'getTemplateUsersViewers',
    'getDefaultTemplates',
    'getProjects',
    'getProjectUsersViewers',
    'getUsers',
    'getProjectGroupsScanners',
    'getProjectPullRequests',
    'getServerSettings',
    'getRules',
    'getTemplateGroupsScanners',
    'getPortfolios',
    'getActiveProfileRules',
    'getGateUsers',
    'getProjectWebhookDeliveries',
    'getNewCodePeriods',
    'getProjectUsersScanners', "getProjectTags",
    'getProjectTasks', 'getRuleDetails', "getProfileBackups",
    'getUserGroups', 'getProjectSettings', 'getTemplateUsersScanners', 'getServerWebhooks',
    'getProjectGroupsViewers', 'getTemplateGroupsViewers', 'getUsage', 'getPluginRules',
    'getApplicationDetails', 'getProjectDetails', 'getProjectTemplateIssues', 'getBranches',
    'getGateGroups', 'getDeactivatedProfileRules', 'getBindings', 'getProjectWebhooks', 'getWebhooks',
    'getProjectIssues', 'getProfiles', 'getProjectBindings', 'getProfileGroups', 'getFixedHotspots',
    'getLabeledIssues', 'getProjectAnalyses', 'getGroups', 'getTemplateRules', 'getPluginIssues',
    'getGateConditions', 'getPlugins', 'getWebhookDeliveries', 'getPortfolioDetails', 'getGates',
    'getUserTokens', 'getProjectPluginIssues', 'getFalsePositiveIssues', 'getRepos', 'getTemplates',
    'getServerInfo']
